/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agregar_gestionar;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katherine Arzate
 */
public class VehiculoGestionar extends javax.swing.JPanel {

    /**
     * Creates new form VehiculoGestionar
     */
    public VehiculoGestionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfIdVehiculo = new javax.swing.JTextField();
        tfMatricula = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        tfMarca = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        tfFabrica = new javax.swing.JTextField();
        tfCosto = new javax.swing.JTextField();
        tfCarga = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Matricula", "Tipo", "Marca", "Modelo", "Fabricado", "Costo", "Carga"
            }
        ));
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);
        if (tblVehiculos.getColumnModel().getColumnCount() > 0) {
            tblVehiculos.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setText("ID del vehiculo:");

        jLabel2.setText("Matricula:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Fabricado:");

        jLabel7.setText("Costo:");

        jLabel8.setText("Carga:");

        tfIdVehiculo.setEditable(false);

        tfCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCargaActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefrescar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfIdVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(tfMatricula)
                                        .addComponent(tfTipo)
                                        .addComponent(tfMarca)))
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(tfCosto)
                                        .addComponent(tfFabrica)
                                        .addComponent(tfModelo)))
                                .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnRefrescar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tfIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCargaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        VehiculoDTO vehiculo = new VehiculoDTO();
        vehiculo.setId_vehiculo(Integer.parseInt(tfIdVehiculo.getText()));
        vehiculo.setMatricula(tfMatricula.getText());
        vehiculo.setTipo(tfTipo.getText());
        vehiculo.setMarca(tfMarca.getText());
        vehiculo.setModelo(tfModelo.getText());
        vehiculo.setFabrica(tfFabrica.getText());
        vehiculo.setCosto(Float.parseFloat(tfFabrica.getText()));
        vehiculo.setCarga(Integer.parseInt(tfCarga.getText()));
        
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas modificarlo?",
                    "Confirmar actualizacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resp == 0){
            Conector cone = new Conector();
            VehiculoDAO vehiculoDAO = new VehiculoDAO(cone.miconector);
            int resultado = vehiculoDAO.actualizarVehiculo(vehiculo);
            
            if(resultado > 0){
                JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                refrescar();
            }else
                JOptionPane.showMessageDialog(null, "Actualizacion erronea");
            cone.cerrar();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        refrescar();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        int r = tblVehiculos.getSelectedRow();
        int id = (int) tblVehiculos.getValueAt(r, 0);
        String matricula = (String) tblVehiculos.getValueAt(r, 1);
        String tipo = (String) tblVehiculos.getValueAt(r, 2);
        String marca = (String) tblVehiculos.getValueAt(r, 3);
        String modelo = (String) tblVehiculos.getValueAt(r, 4);
        String fabrica = (String) tblVehiculos.getValueAt(r, 5);
        float costo = (float) tblVehiculos.getValueAt(r, 6);
        int carga = (int) tblVehiculos.getValueAt(r, 7);
        
        tfIdVehiculo.setText(""+id);
        tfMatricula.setText(matricula);
        tfTipo.setText(tipo);
        tfMarca.setText(marca);
        tfModelo.setText(modelo);
        tfFabrica.setText(fabrica);
        tfCosto.setText(""+costo);
        tfCarga.setText(""+carga);
    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        VehiculoDTO vehiculo = new VehiculoDTO();
        vehiculo.setId_vehiculo(Integer.parseInt(tfIdVehiculo.getText()));
        
        int resp = JOptionPane.showConfirmDialog(null, "¿Realmente deseas eliminar?",
                "Confirmar ELIMINACION", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if(resp == 0){
            Conector cone = new Conector();
            VehiculoDAO vehiculoDAO =new VehiculoDAO(cone.miconector);
            int resultado = vehiculoDAO.borrarVehiculo(vehiculo);
            if(resultado > 0){
                JOptionPane.showMessageDialog(null, "Eliminación exitosa");
                refrescar();
            }else
                JOptionPane.showMessageDialog(null, "Eliminación errónea");
            cone.cerrar();
            
        }
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField tfCarga;
    private javax.swing.JTextField tfCosto;
    private javax.swing.JTextField tfFabrica;
    private javax.swing.JTextField tfIdVehiculo;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables

    private void refrescar() {
        Conector cone = new Conector();
        
        VehiculoDAO vehiculoDAO = new VehiculoDAO(cone.miconector);
        List <VehiculoDTO> vehiculos = vehiculoDAO.vehiculoGeneralDAO();
        
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tblVehiculos.setModel(modeloTabla);
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Matricula");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Fabricado");
        modeloTabla.addColumn("Costo");
        modeloTabla.addColumn("Carga");
        
        Object[] columna = new Object[8];
        
        int objGuardados = vehiculos.size();
        
        for (int i = 0; i < objGuardados; i++) {
            columna[0] = vehiculos.get(i).getId_vehiculo();
            columna[1] = vehiculos.get(i).getMatricula();
            columna[2] = vehiculos.get(i).getTipo();
            columna[3] = vehiculos.get(i).getMarca();
            columna[4] = vehiculos.get(i).getModelo();
            columna[5] = vehiculos.get(i).getFabrica();
            columna[6] = vehiculos.get(i).getCosto();
            columna[7] = vehiculos.get(i).getCarga();
            modeloTabla.addRow(columna);
        }
        cone.cerrar();
    }
}
